# Generated by Django 5.0.1 on 2024-12-25 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_cart_cartitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='cart',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='book',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='CartItem',
        ),
    ]
