# Generated by Django 5.0.1 on 2025-05-28 15:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_alter_category_options_alter_category_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashondeliveryorder',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='books.book'),
        ),
    ]
